/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProtectedPublicRouteRouteImport } from './routes/_protected/_public/route'
import { Route as ProtectedAdminRouteRouteImport } from './routes/_protected/admin/route'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as ProtectedPublicIndexRouteImport } from './routes/_protected/_public/index'
import { Route as ProtectedPublicAddProductRouteImport } from './routes/_protected/_public/add-product'
import { Route as ProtectedPublicProfileRouteImport } from './routes/_protected/_public/profile'
import { Route as ProtectedPublicSearchRouteImport } from './routes/_protected/_public/search'
import { Route as ProtectedPublicStoresRouteImport } from './routes/_protected/_public/stores'
import { Route as ProtectedAdminIndexRouteImport } from './routes/_protected/admin/index'
import { Route as ProtectedAdminAddProductRouteImport } from './routes/_protected/admin/add-product'
import { Route as ProtectedAdminAddStoreRouteImport } from './routes/_protected/admin/add-store'
import { Route as ProtectedAdminAllProductsRouteImport } from './routes/_protected/admin/all-products'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedPublicRouteRoute = ProtectedPublicRouteRouteImport.update({
  id: '/_protected/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAdminRouteRoute = ProtectedAdminRouteRouteImport.update({
  id: '/_protected/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedPublicIndexRoute = ProtectedPublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedPublicRouteRoute,
} as any)
const ProtectedPublicAddProductRoute =
  ProtectedPublicAddProductRouteImport.update({
    id: '/add-product',
    path: '/add-product',
    getParentRoute: () => ProtectedPublicRouteRoute,
  } as any)
const ProtectedPublicProfileRoute = ProtectedPublicProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProtectedPublicRouteRoute,
} as any)
const ProtectedPublicSearchRoute = ProtectedPublicSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ProtectedPublicRouteRoute,
} as any)
const ProtectedPublicStoresRoute = ProtectedPublicStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => ProtectedPublicRouteRoute,
} as any)
const ProtectedAdminIndexRoute = ProtectedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedAdminRouteRoute,
} as any)
const ProtectedAdminAddProductRoute =
  ProtectedAdminAddProductRouteImport.update({
    id: '/add-product',
    path: '/add-product',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)
const ProtectedAdminAddStoreRoute = ProtectedAdminAddStoreRouteImport.update({
  id: '/add-store',
  path: '/add-store',
  getParentRoute: () => ProtectedAdminRouteRoute,
} as any)
const ProtectedAdminAllProductsRoute =
  ProtectedAdminAllProductsRouteImport.update({
    id: '/all-products',
    path: '/all-products',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/': typeof ProtectedPublicIndexRoute
  '/admin': typeof ProtectedAdminRouteRouteWithChildren
  '/products/$productId': typeof ProductsProductIdRoute
  '/add-product': typeof ProtectedPublicAddProductRoute
  '/profile': typeof ProtectedPublicProfileRoute
  '/search': typeof ProtectedPublicSearchRoute
  '/stores': typeof ProtectedPublicStoresRoute
  '/admin/add-product': typeof ProtectedAdminAddProductRoute
  '/admin/add-store': typeof ProtectedAdminAddStoreRoute
  '/admin/all-products': typeof ProtectedAdminAllProductsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/': typeof ProtectedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/add-product': typeof ProtectedPublicAddProductRoute
  '/profile': typeof ProtectedPublicProfileRoute
  '/search': typeof ProtectedPublicSearchRoute
  '/stores': typeof ProtectedPublicStoresRoute
  '/admin/add-product': typeof ProtectedAdminAddProductRoute
  '/admin/add-store': typeof ProtectedAdminAddStoreRoute
  '/admin/all-products': typeof ProtectedAdminAllProductsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/': typeof ProtectedPublicIndexRoute
  '/admin': typeof ProtectedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_protected/_public': typeof ProtectedPublicRouteRouteWithChildren
  '/_protected/admin': typeof ProtectedAdminRouteRouteWithChildren
  '/products/$productId': typeof ProductsProductIdRoute
  '/_protected/_public/add-product': typeof ProtectedPublicAddProductRoute
  '/_protected/_public/profile': typeof ProtectedPublicProfileRoute
  '/_protected/_public/search': typeof ProtectedPublicSearchRoute
  '/_protected/_public/stores': typeof ProtectedPublicStoresRoute
  '/_protected/admin/add-product': typeof ProtectedAdminAddProductRoute
  '/_protected/admin/add-store': typeof ProtectedAdminAddStoreRoute
  '/_protected/admin/all-products': typeof ProtectedAdminAllProductsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_protected/_public/': typeof ProtectedPublicIndexRoute
  '/_protected/admin/': typeof ProtectedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/signup'
    | '/'
    | '/admin'
    | '/products/$productId'
    | '/add-product'
    | '/profile'
    | '/search'
    | '/stores'
    | '/admin/add-product'
    | '/admin/add-store'
    | '/admin/all-products'
    | '/api/auth/$'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/products/$productId'
    | '/add-product'
    | '/profile'
    | '/search'
    | '/stores'
    | '/admin/add-product'
    | '/admin/add-store'
    | '/admin/all-products'
    | '/api/auth/$'
    | '/'
    | '/admin'
  id:
    | '__root__'
    | '/login'
    | '/signup'
    | '/_protected/_public'
    | '/_protected/admin'
    | '/products/$productId'
    | '/_protected/_public/add-product'
    | '/_protected/_public/profile'
    | '/_protected/_public/search'
    | '/_protected/_public/stores'
    | '/_protected/admin/add-product'
    | '/_protected/admin/add-store'
    | '/_protected/admin/all-products'
    | '/api/auth/$'
    | '/_protected/_public/'
    | '/_protected/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ProtectedPublicRouteRoute: typeof ProtectedPublicRouteRouteWithChildren
  ProtectedAdminRouteRoute: typeof ProtectedAdminRouteRouteWithChildren
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/_public': {
      id: '/_protected/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedPublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/admin': {
      id: '/_protected/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/_public/': {
      id: '/_protected/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedPublicIndexRouteImport
      parentRoute: typeof ProtectedPublicRouteRoute
    }
    '/_protected/_public/add-product': {
      id: '/_protected/_public/add-product'
      path: '/add-product'
      fullPath: '/add-product'
      preLoaderRoute: typeof ProtectedPublicAddProductRouteImport
      parentRoute: typeof ProtectedPublicRouteRoute
    }
    '/_protected/_public/profile': {
      id: '/_protected/_public/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedPublicProfileRouteImport
      parentRoute: typeof ProtectedPublicRouteRoute
    }
    '/_protected/_public/search': {
      id: '/_protected/_public/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof ProtectedPublicSearchRouteImport
      parentRoute: typeof ProtectedPublicRouteRoute
    }
    '/_protected/_public/stores': {
      id: '/_protected/_public/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof ProtectedPublicStoresRouteImport
      parentRoute: typeof ProtectedPublicRouteRoute
    }
    '/_protected/admin/': {
      id: '/_protected/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof ProtectedAdminIndexRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/add-product': {
      id: '/_protected/admin/add-product'
      path: '/add-product'
      fullPath: '/admin/add-product'
      preLoaderRoute: typeof ProtectedAdminAddProductRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/add-store': {
      id: '/_protected/admin/add-store'
      path: '/add-store'
      fullPath: '/admin/add-store'
      preLoaderRoute: typeof ProtectedAdminAddStoreRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/all-products': {
      id: '/_protected/admin/all-products'
      path: '/all-products'
      fullPath: '/admin/all-products'
      preLoaderRoute: typeof ProtectedAdminAllProductsRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProtectedPublicRouteRouteChildren {
  ProtectedPublicAddProductRoute: typeof ProtectedPublicAddProductRoute
  ProtectedPublicProfileRoute: typeof ProtectedPublicProfileRoute
  ProtectedPublicSearchRoute: typeof ProtectedPublicSearchRoute
  ProtectedPublicStoresRoute: typeof ProtectedPublicStoresRoute
  ProtectedPublicIndexRoute: typeof ProtectedPublicIndexRoute
}

const ProtectedPublicRouteRouteChildren: ProtectedPublicRouteRouteChildren = {
  ProtectedPublicAddProductRoute: ProtectedPublicAddProductRoute,
  ProtectedPublicProfileRoute: ProtectedPublicProfileRoute,
  ProtectedPublicSearchRoute: ProtectedPublicSearchRoute,
  ProtectedPublicStoresRoute: ProtectedPublicStoresRoute,
  ProtectedPublicIndexRoute: ProtectedPublicIndexRoute,
}

const ProtectedPublicRouteRouteWithChildren =
  ProtectedPublicRouteRoute._addFileChildren(ProtectedPublicRouteRouteChildren)

interface ProtectedAdminRouteRouteChildren {
  ProtectedAdminAddProductRoute: typeof ProtectedAdminAddProductRoute
  ProtectedAdminAddStoreRoute: typeof ProtectedAdminAddStoreRoute
  ProtectedAdminAllProductsRoute: typeof ProtectedAdminAllProductsRoute
  ProtectedAdminIndexRoute: typeof ProtectedAdminIndexRoute
}

const ProtectedAdminRouteRouteChildren: ProtectedAdminRouteRouteChildren = {
  ProtectedAdminAddProductRoute: ProtectedAdminAddProductRoute,
  ProtectedAdminAddStoreRoute: ProtectedAdminAddStoreRoute,
  ProtectedAdminAllProductsRoute: ProtectedAdminAllProductsRoute,
  ProtectedAdminIndexRoute: ProtectedAdminIndexRoute,
}

const ProtectedAdminRouteRouteWithChildren =
  ProtectedAdminRouteRoute._addFileChildren(ProtectedAdminRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ProtectedPublicRouteRoute: ProtectedPublicRouteRouteWithChildren,
  ProtectedAdminRouteRoute: ProtectedAdminRouteRouteWithChildren,
  ProductsProductIdRoute: ProductsProductIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
