/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProtectedPublicRouteRouteImport } from './routes/_protected/_public/route'
import { Route as ProtectedAdminRouteRouteImport } from './routes/_protected/admin/route'
import { Route as ProtectedPublicIndexRouteImport } from './routes/_protected/_public/index'
import { Route as ProtectedPublicAddProductRouteImport } from './routes/_protected/_public/add-product'
import { Route as ProtectedPublicProfileRouteImport } from './routes/_protected/_public/profile'
import { Route as ProtectedPublicSearchRouteImport } from './routes/_protected/_public/search'
import { Route as ProtectedAdminAddCategoryRouteImport } from './routes/_protected/admin/add-category'
import { Route as ProtectedAdminAddProductRouteImport } from './routes/_protected/admin/add-product'
import { Route as ProtectedAdminAddStoreRouteImport } from './routes/_protected/admin/add-store'
import { Route as ProtectedAdminAllCategoriesRouteImport } from './routes/_protected/admin/all-categories'
import { Route as ProtectedAdminAllProductsRouteImport } from './routes/_protected/admin/all-products'
import { Route as ProtectedAdminCategoryMappingsRouteImport } from './routes/_protected/admin/category-mappings'
import { Route as ProtectedAdminIngredientMappingsRouteImport } from './routes/_protected/admin/ingredient-mappings'
import { Route as ProtectedAdminIngredientsRouteImport } from './routes/_protected/admin/ingredients'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedPublicProductsProductIdRouteImport } from './routes/_protected/_public/products/$productId'
import { Route as ProtectedPublicStoresIndexRouteImport } from './routes/_protected/_public/stores/index'
import { Route as ProtectedPublicStoresStoreIdIndexRouteImport } from './routes/_protected/_public/stores/$storeId/index'
import { Route as ProtectedPublicStoresStoreIdCategoryIdRouteImport } from './routes/_protected/_public/stores/$storeId/$categoryId'

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedPublicRouteRoute = ProtectedPublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedAdminRouteRoute = ProtectedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedPublicIndexRoute = ProtectedPublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedPublicRouteRoute,
} as any)
const ProtectedPublicAddProductRoute =
  ProtectedPublicAddProductRouteImport.update({
    id: '/add-product',
    path: '/add-product',
    getParentRoute: () => ProtectedPublicRouteRoute,
  } as any)
const ProtectedPublicProfileRoute = ProtectedPublicProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProtectedPublicRouteRoute,
} as any)
const ProtectedPublicSearchRoute = ProtectedPublicSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ProtectedPublicRouteRoute,
} as any)
const ProtectedAdminAddCategoryRoute =
  ProtectedAdminAddCategoryRouteImport.update({
    id: '/add-category',
    path: '/add-category',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)
const ProtectedAdminAddProductRoute =
  ProtectedAdminAddProductRouteImport.update({
    id: '/add-product',
    path: '/add-product',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)
const ProtectedAdminAddStoreRoute = ProtectedAdminAddStoreRouteImport.update({
  id: '/add-store',
  path: '/add-store',
  getParentRoute: () => ProtectedAdminRouteRoute,
} as any)
const ProtectedAdminAllCategoriesRoute =
  ProtectedAdminAllCategoriesRouteImport.update({
    id: '/all-categories',
    path: '/all-categories',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)
const ProtectedAdminAllProductsRoute =
  ProtectedAdminAllProductsRouteImport.update({
    id: '/all-products',
    path: '/all-products',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)
const ProtectedAdminCategoryMappingsRoute =
  ProtectedAdminCategoryMappingsRouteImport.update({
    id: '/category-mappings',
    path: '/category-mappings',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)
const ProtectedAdminIngredientMappingsRoute =
  ProtectedAdminIngredientMappingsRouteImport.update({
    id: '/ingredient-mappings',
    path: '/ingredient-mappings',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)
const ProtectedAdminIngredientsRoute =
  ProtectedAdminIngredientsRouteImport.update({
    id: '/ingredients',
    path: '/ingredients',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedPublicProductsProductIdRoute =
  ProtectedPublicProductsProductIdRouteImport.update({
    id: '/products/$productId',
    path: '/products/$productId',
    getParentRoute: () => ProtectedPublicRouteRoute,
  } as any)
const ProtectedPublicStoresIndexRoute =
  ProtectedPublicStoresIndexRouteImport.update({
    id: '/stores/',
    path: '/stores/',
    getParentRoute: () => ProtectedPublicRouteRoute,
  } as any)
const ProtectedPublicStoresStoreIdIndexRoute =
  ProtectedPublicStoresStoreIdIndexRouteImport.update({
    id: '/stores/$storeId/',
    path: '/stores/$storeId/',
    getParentRoute: () => ProtectedPublicRouteRoute,
  } as any)
const ProtectedPublicStoresStoreIdCategoryIdRoute =
  ProtectedPublicStoresStoreIdCategoryIdRouteImport.update({
    id: '/stores/$storeId/$categoryId',
    path: '/stores/$storeId/$categoryId',
    getParentRoute: () => ProtectedPublicRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedPublicIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof ProtectedAdminRouteRouteWithChildren
  '/add-product': typeof ProtectedPublicAddProductRoute
  '/profile': typeof ProtectedPublicProfileRoute
  '/search': typeof ProtectedPublicSearchRoute
  '/admin/add-category': typeof ProtectedAdminAddCategoryRoute
  '/admin/add-product': typeof ProtectedAdminAddProductRoute
  '/admin/add-store': typeof ProtectedAdminAddStoreRoute
  '/admin/all-categories': typeof ProtectedAdminAllCategoriesRoute
  '/admin/all-products': typeof ProtectedAdminAllProductsRoute
  '/admin/category-mappings': typeof ProtectedAdminCategoryMappingsRoute
  '/admin/ingredient-mappings': typeof ProtectedAdminIngredientMappingsRoute
  '/admin/ingredients': typeof ProtectedAdminIngredientsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/products/$productId': typeof ProtectedPublicProductsProductIdRoute
  '/stores/': typeof ProtectedPublicStoresIndexRoute
  '/stores/$storeId/$categoryId': typeof ProtectedPublicStoresStoreIdCategoryIdRoute
  '/stores/$storeId/': typeof ProtectedPublicStoresStoreIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ProtectedPublicIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof ProtectedAdminRouteRouteWithChildren
  '/add-product': typeof ProtectedPublicAddProductRoute
  '/profile': typeof ProtectedPublicProfileRoute
  '/search': typeof ProtectedPublicSearchRoute
  '/admin/add-category': typeof ProtectedAdminAddCategoryRoute
  '/admin/add-product': typeof ProtectedAdminAddProductRoute
  '/admin/add-store': typeof ProtectedAdminAddStoreRoute
  '/admin/all-categories': typeof ProtectedAdminAllCategoriesRoute
  '/admin/all-products': typeof ProtectedAdminAllProductsRoute
  '/admin/category-mappings': typeof ProtectedAdminCategoryMappingsRoute
  '/admin/ingredient-mappings': typeof ProtectedAdminIngredientMappingsRoute
  '/admin/ingredients': typeof ProtectedAdminIngredientsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/products/$productId': typeof ProtectedPublicProductsProductIdRoute
  '/stores': typeof ProtectedPublicStoresIndexRoute
  '/stores/$storeId/$categoryId': typeof ProtectedPublicStoresStoreIdCategoryIdRoute
  '/stores/$storeId': typeof ProtectedPublicStoresStoreIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_protected/_public': typeof ProtectedPublicRouteRouteWithChildren
  '/_protected/admin': typeof ProtectedAdminRouteRouteWithChildren
  '/_protected/_public/add-product': typeof ProtectedPublicAddProductRoute
  '/_protected/_public/profile': typeof ProtectedPublicProfileRoute
  '/_protected/_public/search': typeof ProtectedPublicSearchRoute
  '/_protected/admin/add-category': typeof ProtectedAdminAddCategoryRoute
  '/_protected/admin/add-product': typeof ProtectedAdminAddProductRoute
  '/_protected/admin/add-store': typeof ProtectedAdminAddStoreRoute
  '/_protected/admin/all-categories': typeof ProtectedAdminAllCategoriesRoute
  '/_protected/admin/all-products': typeof ProtectedAdminAllProductsRoute
  '/_protected/admin/category-mappings': typeof ProtectedAdminCategoryMappingsRoute
  '/_protected/admin/ingredient-mappings': typeof ProtectedAdminIngredientMappingsRoute
  '/_protected/admin/ingredients': typeof ProtectedAdminIngredientsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_protected/_public/': typeof ProtectedPublicIndexRoute
  '/_protected/_public/products/$productId': typeof ProtectedPublicProductsProductIdRoute
  '/_protected/_public/stores/': typeof ProtectedPublicStoresIndexRoute
  '/_protected/_public/stores/$storeId/$categoryId': typeof ProtectedPublicStoresStoreIdCategoryIdRoute
  '/_protected/_public/stores/$storeId/': typeof ProtectedPublicStoresStoreIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/admin'
    | '/add-product'
    | '/profile'
    | '/search'
    | '/admin/add-category'
    | '/admin/add-product'
    | '/admin/add-store'
    | '/admin/all-categories'
    | '/admin/all-products'
    | '/admin/category-mappings'
    | '/admin/ingredient-mappings'
    | '/admin/ingredients'
    | '/api/auth/$'
    | '/products/$productId'
    | '/stores/'
    | '/stores/$storeId/$categoryId'
    | '/stores/$storeId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/admin'
    | '/add-product'
    | '/profile'
    | '/search'
    | '/admin/add-category'
    | '/admin/add-product'
    | '/admin/add-store'
    | '/admin/all-categories'
    | '/admin/all-products'
    | '/admin/category-mappings'
    | '/admin/ingredient-mappings'
    | '/admin/ingredients'
    | '/api/auth/$'
    | '/products/$productId'
    | '/stores'
    | '/stores/$storeId/$categoryId'
    | '/stores/$storeId'
  id:
    | '__root__'
    | '/_protected'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/_protected/_public'
    | '/_protected/admin'
    | '/_protected/_public/add-product'
    | '/_protected/_public/profile'
    | '/_protected/_public/search'
    | '/_protected/admin/add-category'
    | '/_protected/admin/add-product'
    | '/_protected/admin/add-store'
    | '/_protected/admin/all-categories'
    | '/_protected/admin/all-products'
    | '/_protected/admin/category-mappings'
    | '/_protected/admin/ingredient-mappings'
    | '/_protected/admin/ingredients'
    | '/api/auth/$'
    | '/_protected/_public/'
    | '/_protected/_public/products/$productId'
    | '/_protected/_public/stores/'
    | '/_protected/_public/stores/$storeId/$categoryId'
    | '/_protected/_public/stores/$storeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/_public': {
      id: '/_protected/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedPublicRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/admin': {
      id: '/_protected/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/_public/': {
      id: '/_protected/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedPublicIndexRouteImport
      parentRoute: typeof ProtectedPublicRouteRoute
    }
    '/_protected/_public/add-product': {
      id: '/_protected/_public/add-product'
      path: '/add-product'
      fullPath: '/add-product'
      preLoaderRoute: typeof ProtectedPublicAddProductRouteImport
      parentRoute: typeof ProtectedPublicRouteRoute
    }
    '/_protected/_public/profile': {
      id: '/_protected/_public/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedPublicProfileRouteImport
      parentRoute: typeof ProtectedPublicRouteRoute
    }
    '/_protected/_public/search': {
      id: '/_protected/_public/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof ProtectedPublicSearchRouteImport
      parentRoute: typeof ProtectedPublicRouteRoute
    }
    '/_protected/admin/add-category': {
      id: '/_protected/admin/add-category'
      path: '/add-category'
      fullPath: '/admin/add-category'
      preLoaderRoute: typeof ProtectedAdminAddCategoryRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/add-product': {
      id: '/_protected/admin/add-product'
      path: '/add-product'
      fullPath: '/admin/add-product'
      preLoaderRoute: typeof ProtectedAdminAddProductRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/add-store': {
      id: '/_protected/admin/add-store'
      path: '/add-store'
      fullPath: '/admin/add-store'
      preLoaderRoute: typeof ProtectedAdminAddStoreRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/all-categories': {
      id: '/_protected/admin/all-categories'
      path: '/all-categories'
      fullPath: '/admin/all-categories'
      preLoaderRoute: typeof ProtectedAdminAllCategoriesRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/all-products': {
      id: '/_protected/admin/all-products'
      path: '/all-products'
      fullPath: '/admin/all-products'
      preLoaderRoute: typeof ProtectedAdminAllProductsRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/category-mappings': {
      id: '/_protected/admin/category-mappings'
      path: '/category-mappings'
      fullPath: '/admin/category-mappings'
      preLoaderRoute: typeof ProtectedAdminCategoryMappingsRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/ingredient-mappings': {
      id: '/_protected/admin/ingredient-mappings'
      path: '/ingredient-mappings'
      fullPath: '/admin/ingredient-mappings'
      preLoaderRoute: typeof ProtectedAdminIngredientMappingsRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/ingredients': {
      id: '/_protected/admin/ingredients'
      path: '/ingredients'
      fullPath: '/admin/ingredients'
      preLoaderRoute: typeof ProtectedAdminIngredientsRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/_public/products/$productId': {
      id: '/_protected/_public/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProtectedPublicProductsProductIdRouteImport
      parentRoute: typeof ProtectedPublicRouteRoute
    }
    '/_protected/_public/stores/': {
      id: '/_protected/_public/stores/'
      path: '/stores'
      fullPath: '/stores/'
      preLoaderRoute: typeof ProtectedPublicStoresIndexRouteImport
      parentRoute: typeof ProtectedPublicRouteRoute
    }
    '/_protected/_public/stores/$storeId/': {
      id: '/_protected/_public/stores/$storeId/'
      path: '/stores/$storeId'
      fullPath: '/stores/$storeId/'
      preLoaderRoute: typeof ProtectedPublicStoresStoreIdIndexRouteImport
      parentRoute: typeof ProtectedPublicRouteRoute
    }
    '/_protected/_public/stores/$storeId/$categoryId': {
      id: '/_protected/_public/stores/$storeId/$categoryId'
      path: '/stores/$storeId/$categoryId'
      fullPath: '/stores/$storeId/$categoryId'
      preLoaderRoute: typeof ProtectedPublicStoresStoreIdCategoryIdRouteImport
      parentRoute: typeof ProtectedPublicRouteRoute
    }
  }
}

interface ProtectedPublicRouteRouteChildren {
  ProtectedPublicAddProductRoute: typeof ProtectedPublicAddProductRoute
  ProtectedPublicProfileRoute: typeof ProtectedPublicProfileRoute
  ProtectedPublicSearchRoute: typeof ProtectedPublicSearchRoute
  ProtectedPublicIndexRoute: typeof ProtectedPublicIndexRoute
  ProtectedPublicProductsProductIdRoute: typeof ProtectedPublicProductsProductIdRoute
  ProtectedPublicStoresIndexRoute: typeof ProtectedPublicStoresIndexRoute
  ProtectedPublicStoresStoreIdCategoryIdRoute: typeof ProtectedPublicStoresStoreIdCategoryIdRoute
  ProtectedPublicStoresStoreIdIndexRoute: typeof ProtectedPublicStoresStoreIdIndexRoute
}

const ProtectedPublicRouteRouteChildren: ProtectedPublicRouteRouteChildren = {
  ProtectedPublicAddProductRoute: ProtectedPublicAddProductRoute,
  ProtectedPublicProfileRoute: ProtectedPublicProfileRoute,
  ProtectedPublicSearchRoute: ProtectedPublicSearchRoute,
  ProtectedPublicIndexRoute: ProtectedPublicIndexRoute,
  ProtectedPublicProductsProductIdRoute: ProtectedPublicProductsProductIdRoute,
  ProtectedPublicStoresIndexRoute: ProtectedPublicStoresIndexRoute,
  ProtectedPublicStoresStoreIdCategoryIdRoute:
    ProtectedPublicStoresStoreIdCategoryIdRoute,
  ProtectedPublicStoresStoreIdIndexRoute:
    ProtectedPublicStoresStoreIdIndexRoute,
}

const ProtectedPublicRouteRouteWithChildren =
  ProtectedPublicRouteRoute._addFileChildren(ProtectedPublicRouteRouteChildren)

interface ProtectedAdminRouteRouteChildren {
  ProtectedAdminAddCategoryRoute: typeof ProtectedAdminAddCategoryRoute
  ProtectedAdminAddProductRoute: typeof ProtectedAdminAddProductRoute
  ProtectedAdminAddStoreRoute: typeof ProtectedAdminAddStoreRoute
  ProtectedAdminAllCategoriesRoute: typeof ProtectedAdminAllCategoriesRoute
  ProtectedAdminAllProductsRoute: typeof ProtectedAdminAllProductsRoute
  ProtectedAdminCategoryMappingsRoute: typeof ProtectedAdminCategoryMappingsRoute
  ProtectedAdminIngredientMappingsRoute: typeof ProtectedAdminIngredientMappingsRoute
  ProtectedAdminIngredientsRoute: typeof ProtectedAdminIngredientsRoute
}

const ProtectedAdminRouteRouteChildren: ProtectedAdminRouteRouteChildren = {
  ProtectedAdminAddCategoryRoute: ProtectedAdminAddCategoryRoute,
  ProtectedAdminAddProductRoute: ProtectedAdminAddProductRoute,
  ProtectedAdminAddStoreRoute: ProtectedAdminAddStoreRoute,
  ProtectedAdminAllCategoriesRoute: ProtectedAdminAllCategoriesRoute,
  ProtectedAdminAllProductsRoute: ProtectedAdminAllProductsRoute,
  ProtectedAdminCategoryMappingsRoute: ProtectedAdminCategoryMappingsRoute,
  ProtectedAdminIngredientMappingsRoute: ProtectedAdminIngredientMappingsRoute,
  ProtectedAdminIngredientsRoute: ProtectedAdminIngredientsRoute,
}

const ProtectedAdminRouteRouteWithChildren =
  ProtectedAdminRouteRoute._addFileChildren(ProtectedAdminRouteRouteChildren)

interface ProtectedRouteRouteChildren {
  ProtectedPublicRouteRoute: typeof ProtectedPublicRouteRouteWithChildren
  ProtectedAdminRouteRoute: typeof ProtectedAdminRouteRouteWithChildren
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedPublicRouteRoute: ProtectedPublicRouteRouteWithChildren,
  ProtectedAdminRouteRoute: ProtectedAdminRouteRouteWithChildren,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
